version: 2
updates:
  # Atualizações do npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "@otomiranda"
    assignees:
      - "@otomiranda"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Agrupar atualizações menores
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      radix-ui:
        patterns:
          - "@radix-ui/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
        dependency-type: "development"
    # Ignorar algumas atualizações específicas
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Atualizações do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "@otomiranda"
    assignees:
      - "@otomiranda"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

  # Atualizações do Docker (se houver Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "@otomiranda"
    assignees:
      - "@otomiranda"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "automated"